version: '3.8'

services:
  food-delivery:
    image: prakhar9918/food-delivery:latest
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://admin:qwerty@mongodb:27017/"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "qwerty"
      ME_CONFIG_MONGODB_URL: "mongodb://admin:qwerty@mongodb:27017/"
